# Generated by Django 6.0.4 on 2026-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_recipe_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='absent',
            field=models.BooleanField(default=False, help_text='Personne ne mange à la maison pour ce créneau (cantine, travail…).', verbose_name='Repas absent'),
        ),
    ]
