# Generated by Django 6.0.4 on 2026-04-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_ciqual_ingredientref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='openfoodfacts_id',
        ),
        migrations.AlterField(
            model_name='ingredientref',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
