# Generated by Django 6.0.4 on 2026-05-02 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_synonymes_ingredientref'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('nom_normalise', models.CharField(db_index=True, editable=False, max_length=200, verbose_name='Nom normalisé')),
                ('synonymes', models.TextField(blank=True, default='', help_text='Noms alternatifs séparés par des virgules (insensible à la casse et aux accents)', verbose_name='Synonymes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ciqual_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='known_ingredients', to='menu.ingredientref', verbose_name='Référence Ciqual')),
            ],
            options={
                'verbose_name': 'Ingrédient connu',
                'verbose_name_plural': 'Ingrédients connus',
                'ordering': ['name'],
            },
        ),
    ]
