# Generated by Django 6.0.4 on 2026-05-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_known_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='known_ingredient',
            field=models.ForeignKey(blank=True, help_text='Lien vers la base de connaissance ingrédients', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='menu.knowningredient', verbose_name='Ingrédient connu'),
        ),
        migrations.AddField(
            model_name='knowningredient',
            name='default_unit',
            field=models.CharField(blank=True, default='g', help_text='Ex. g, ml, kg, unité — pré-remplit le champ Unité dans le formulaire recette', max_length=20, verbose_name='Unité par défaut'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ciqual_ref',
            field=models.ForeignKey(blank=True, help_text='Dérivé automatiquement depuis known_ingredient.ciqual_ref à la sauvegarde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='menu.ingredientref', verbose_name='Référence Ciqual'),
        ),
    ]
