# Generated by Django 6.0.4 on 2026-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_ingredientref_new_nutrition_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sugars_per_serving',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
