# Generated by Django 6.0.4 on 2026-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_weekplan_flexible_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='kcal_per_100g_raw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
