# Generated by Django 6.0.4 on 2026-05-04 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_kcal_per_100g_raw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='guest_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_members',
            field=models.ManyToManyField(blank=True, related_name='meal_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
