# Generated by Django 6.0.4 on 2026-05-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_meal_members_and_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='breakfast_kcal',
            field=models.PositiveIntegerField(default=500, verbose_name='Petit-déjeuner (kcal)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_prot_target',
            field=models.PositiveIntegerField(default=75, verbose_name='Protéines totales cible (g/jour)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dinner_kcal_target',
            field=models.PositiveIntegerField(default=650, verbose_name='Dîner cible (kcal)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lunch_kcal_target',
            field=models.PositiveIntegerField(default=650, verbose_name='Déjeuner cible (kcal)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_kcal',
            field=models.PositiveIntegerField(default=0, verbose_name='Autres apports (kcal)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='snack_kcal',
            field=models.PositiveIntegerField(default=200, verbose_name='Collation (kcal)'),
        ),
    ]
