# Generated by Django 6.0.4 on 2026-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_userprofile_nutrition_targets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='daily_prot_target',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='breakfast_prot',
            field=models.PositiveIntegerField(default=15, verbose_name='Petit-déjeuner (g prot)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dinner_prot_target',
            field=models.PositiveIntegerField(default=25, verbose_name='Dîner cible (g prot)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lunch_prot_target',
            field=models.PositiveIntegerField(default=25, verbose_name='Déjeuner cible (g prot)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other_prot',
            field=models.PositiveIntegerField(default=2, verbose_name='Autres apports (g prot)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Profil type PNNS'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='snack_prot',
            field=models.PositiveIntegerField(default=8, verbose_name='Collation (g prot)'),
        ),
    ]
