# Generated by Django 6.0.4 on 2026-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_knowningredient_transco_unit_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientref',
            name='protein_type',
            field=models.CharField(blank=True, choices=[('boeuf', 'Bœuf'), ('veau', 'Veau'), ('volaille', 'Volaille'), ('porc', 'Porc'), ('poisson', 'Poisson'), ('oeufs', 'Œufs'), ('legumineuses', 'Légumineuses'), ('autre', 'Autre')], max_length=20, null=True, verbose_name='Type de protéine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat'), ('accompagnement', 'Accompagnement'), ('sauce', 'Sauce'), ('dessert', 'Dessert'), ('brunch', 'Brunch'), ('snack', 'Snack')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein_type',
            field=models.CharField(blank=True, choices=[('boeuf', 'Bœuf'), ('veau', 'Veau'), ('volaille', 'Volaille'), ('porc', 'Porc'), ('poisson', 'Poisson'), ('oeufs', 'Œufs'), ('legumineuses', 'Légumineuses'), ('autre', 'Autre'), ('aucune', 'Aucune (végétarien)')], max_length=20, null=True, verbose_name='Protéine principale'),
        ),
    ]
