# Generated by Django 6.0.4 on 2026-08-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_alter_ingredientref_protein_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='familles_secondaires',
            field=models.ManyToManyField(blank=True, help_text="Ex. enfant en garde alternée, membre d'une famille principale et présent/sélectionnable dans le planning d'une ou plusieurs autres familles.", related_name='membres_secondaires', to='menu.family', verbose_name='Familles secondaires'),
        ),
    ]
